ecommerce/cart/urls.py
from django.conf.urls import url
from .views import cart_home,cart_update,checkout_home
app_name='cart'
urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^update/$', cart_update, name='update'),
    url(r'^checkout/$', checkout_home, name='checkout'),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from cart.views import cart_home
from products.views import ProductFeaturedListView,ProductFeaturedDetailView
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.home_page,name='home_page'),
    url(r'^contact/$',views.contact_page,name='contact_page'),
    url(r'^login/$',views.login_page,name='login_page'),
    url(r'^logout/$',views.logout_page,name='logout_page'),
    url(r'^register/$', views.register_page, name='register_page'),
    url(r'^products/',include("products.urls")),
    url(r'^search/', include("search.urls", namespace="search")),
    # url(r'^products/$', ProductListView.as_view(), name='product_list'),
    # # url(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view(), name='product_detail'),
    # url(r'^products/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='product_slug_detail'),
    url(r'^featured/$', ProductFeaturedListView.as_view(), name='product_featured_list'),
    url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view(), name='product_featured_detail'),
    url(r'^cart/',include("cart.urls", namespace="cart")),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root= settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

ecommerce/products/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import ProductListView,ProductDetailSlugView
from . import views

urlpatterns = [

    url(r'^$', ProductListView.as_view(), name='product_list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='product_slug_detail'),

]

ecommerce/products/models.py
from django.db import models
import random
import os
from django.db.models import Q
from django.db.models.signals import pre_save,post_save
from .utils import unique_slug_generator
def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name,ext = os.path.splitext(base_name)
    return name, ext

def upload_image_path(instance, filename):
    print(instance)
    print(filename)
    new_filename = random.randint(1,75435643456)
    name, ext = get_filename_ext(filename)
    final_filename = '{0}{1}'.format(new_filename,ext)
    return f"products/{new_filename}/{final_filename}"



# Create your models here.
class ProductQuerySet(models.query.QuerySet):
    def featured(self):
        return self.filter(featured=True)
    def searched(self,query):
        #return self.filter(title__icontains=query)
        lookups = Q(title__icontains=query) | Q(description__icontains=query)
        return self.filter(lookups).distinct()

class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model,using=self._db)
    def featured(self):
        return self.get_queryset().featured()
    def searched(self,query):
        return self.get_queryset().searched(query)


class product(models.Model):
    title = models.CharField(max_length=20)
    slug = models.SlugField(default='abc', blank=True, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=20,default=39.99, decimal_places=2)
    image = models.ImageField(upload_to=upload_image_path, null=True)
    featured = models.BooleanField(default=False)
    def __str__(self):
        return self.title
    objects = ProductManager()

    def get_absolute_url(self):
        return "/products/{slug}/".format(slug=self.slug)



def product_pre_save_receiver(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug=unique_slug_generator(instance)

pre_save.connect(product_pre_save_receiver,sender=product)

ecommerce/products/views.py
from django.shortcuts import render
from django.views import generic
from .models import product,ProductManager
from cart.models import Cart
# Create your views here.
class ProductListView(generic.ListView):
    queryset = product.objects.all()
    def get_context_data(self, *args, **kwargs):
        context = super(ProductListView,self).get_context_data(*args,**kwargs)
        print(context)
        return context

class ProductDetailView(generic.DetailView):
    model = product


class ProductFeaturedListView(generic.ListView):
    template_name = 'products/product_list.html'
    queryset = product.objects.featured()
    # def get_queryset(self,*args,**kwargs):
    #     request = self.request
    #     return product.objects.featured()

class ProductFeaturedDetailView(generic.DetailView):
    template_name = 'products/product_detail.html'
    queryset = product.objects.featured()
    # def get_queryset(self,*args,**kwargs):
    #     request = self.request
    #     return product.objects.featured()

class ProductDetailSlugView(generic.DetailView):
    template_name = 'products/product_detail.html'
    queryset = product.objects.all()

    def get_context_data(self, *args, **kwargs):
        request=self.request
        context = super(ProductDetailSlugView,self).get_context_data(*args,**kwargs)
        cart_obj,new_obj = Cart.objects.new_or_get(request)
        context['cart'] = cart_obj
        return context

ecommerce/products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="col-12 col-md-6">
    {%include 'products/update_cart.html' with product=object cart=cart %}
    </div>
<div class="text-center">
{{object.title}} <br />
<img src='{{object.image.url}}' />
    </div>



{% endblock %}

ecommerce/products/templates/products/product_list.html
{% extends "base.html" %}
{% block content %}
<div class="row">
{% for obj in object_list %}
<div class="col">
    {{forloop.counter}}
{% include 'products/snippets/card.html' with instance=obj %}
   {% if forloop.counter|divisibleby:2 %}
</div></div><div class = "row"><div class="col-12" ></div>
    {% else %}
</div>
{% endif %}

{% endfor %}
</div>
{% endblock %}

ecommerce/products/templates/products/update_cart.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<form method='POST' action='{%url "cart:update" %}' class="form">
    {%csrf_token%}
    <input type="hidden" name="product_id" value="{{product.id}}" />
    {%if in_cart is  True %}
        <button class ='btn btn-link btn-sm' type="submit"><i class="fa fa-trash" aria-hidden="true"></i></button>

    {%else %}
        {% if product in cart.products.all %}

        In Cart

        <button class ='btn btn-link' type="submit">Remove</button>
        {% else %}
         <button class ='btn btn-success'>Add to Cart</button>
        {%endif %}
    {%endif%}
</div>
</form>