ecommerce/cart/urls.py
from django.conf.urls import url
from .views import cart_home,cart_update,checkout_home
app_name='cart'
urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^update/$', cart_update, name='update'),
    url(r'^checkout/$', checkout_home, name='checkout'),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from cart.views import cart_home
from products.views import ProductFeaturedListView,ProductFeaturedDetailView
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.home_page,name='home_page'),
    url(r'^contact/$',views.contact_page,name='contact_page'),
    url(r'^login/$',views.login_page,name='login_page'),
    url(r'^logout/$',views.logout_page,name='logout_page'),
    url(r'^register/$', views.register_page, name='register_page'),
    url(r'^products/',include("products.urls")),
    url(r'^search/', include("search.urls", namespace="search")),
    # url(r'^products/$', ProductListView.as_view(), name='product_list'),
    # # url(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view(), name='product_detail'),
    # url(r'^products/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='product_slug_detail'),
    url(r'^featured/$', ProductFeaturedListView.as_view(), name='product_featured_list'),
    url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view(), name='product_featured_detail'),
    url(r'^cart/',include("cart.urls", namespace="cart")),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root= settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.urls import path
from django.conf.urls import url
from .views import SearchProductView
from django.conf import settings
from django.conf.urls.static import static
from products.views import ProductListView
from . import views
app_name='search'
urlpatterns = [

    url(r'^$', SearchProductView.as_view(), name='query'),

]

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
</head>
<body>
{% include 'navbar.html' %}
<div class="text-center">
<h1>{{title}}</h1>
        </div>
<div class="container">
    <div class="row">
        <div class="col">
{% block content %}
{% endblock %}
      </div>
</div>

</div>
</body>
</html>

ecommerce/templates/home_page.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="text-center">
    <h1> Hello World, we're working</h1>
</div>

<img src = '{%static "img/dog.jpg" %}' />
{% endblock %}

ecommerce/templates/navbar.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <p class="navbar-brand">Hello {% if request.user.is_authenticated %}{{request.user}}{% else %}Guest{% endif %}</p>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home_page' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contact_page' %}">Contact Us</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'product_list' %}">Products</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:home' %}"><i class="fa fa-shopping-cart" aria-hidden="true"></i> {{request.session.cart_items}}</a>
      </li>

        {% if request.user.is_authenticated %}
         <li class="nav-item">
        <a class="nav-link" href="{% url 'logout_page' %}">Logout</a>

        {% else %}
         <li class="nav-item">
        <a class="nav-link" href="{% url 'login_page' %}">Login</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'register_page' %}">Register</a>
      </li>
        {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search:query' %}">
      <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>